name: sims_ppob
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  formz: ^0.6.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  email_validator: ^2.1.17
  smooth_page_indicator: ^1.1.0
  go_router: ^10.1.2
  flutter_native_splash: ^2.3.2
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  go_router_builder: ^2.3.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: plusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700